apiVersion: v1
kind: PersistentVolume
metadata:
  name: vending-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  hostPath:
    path: /home/pi/alvin/DevOps/src/sqlite-data  # Path on Raspberry Pi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vending-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
