apiVersion: v1
kind: Service
metadata:
  name: vending-app-service
spec:
  type: NodePort
  selector:
    app: vending-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30001   # Manually assigned fixed NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: vending-admin-service
spec:
  type: NodePort
  selector:
    app: vending-admin
  ports:
    - protocol: TCP
      port: 81
      targetPort: 5002
      nodePort: 30002   # Manually assigned fixed NodePort

